### ISSUE TITLE
网站biggsai.com无法访问哦~

### ISSUE THREAD

**Issue by 0xca71** [javasmall/bigsai-algorithm#1]
大佬写的非常好，我直接学习一波哈哈哈哈哈！！！！
域名能ping通，但是浏览器没响应呢，http和https都不行
![image](https://user-images.githubusercontent.com/45744184/131473284-e45b82ad-dd04-4159-8155-65f2dc881327.png)

**Comment by javasmall** [comment]
enum 抱歉才看issue，当时是因为那个是我第一个域名后来不用了哈哈
